queue_rules:
  - name: Dependency Updates
    merge_method: squash
    queue_conditions:
      - check-success = Run tests
      - author = dependabot[bot]
    merge_conditions:
      - check-success = Run tests
pull_request_rules:
  - name: Auto approve dependabot PRs
    conditions:
      - author = dependabot[bot]
      - check-success = Run tests
      - check-success = Run linters
    actions:
      review:
        type: APPROVE
        message: Automatically approved
  - name: Queue dependency updates
    conditions:
      - author = dependabot[bot]
    actions:
      queue:
  - name: Delete merged feature branches
    conditions:
      - merged
      - head ~= feature/.*
    actions:
      delete_head_branch:
