queue_rules:
  - name: Dependency Updates
    merge_method: squash
    queue_conditions:
      - check-success = Run tests
      - author = dependabot[bot]
    merge_conditions:
      - check-success = Run tests
    branch_protection_injection_mode: none

pull_request_rules:
  - name: Delete merged branches
    conditions:
      - merged
    actions:
        delete_head_branch:
      