# fly.toml app configuration file generated for proxy-hltb on 2024-10-06T00:36:20-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proxy-hltb'
primary_region = 'gru'

[build]
  image = 'ghcr.io/kennedyoliveira/hltb-proxy:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 8080
  path = '/metrics'
