apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hltb-proxy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hltb-proxy
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        # Target CPU utilization percentage
        target:
          type: Utilization
          averageUtilization: 70