apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - prometheus-monitor.yaml
  - hpa.yaml

labels:
  - pairs:
      app.kubernetes.io/name: hltb-proxy
      app.kubernetes.io/instance: hltb-proxy
    includeSelectors: true
    includeTemplates: true

images:
  - name: ghcr.io/kennedyoliveira/hltb-proxy
    newTag: 0.2.0

namespace: hltb-proxy