name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  run-linters:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: cargo, rustc
          toolchain: stable

      - name: Install just
        run: cargo install just

      - name: Install pre-requisites
        run: just install-prereqs

      - name: Tests
        run: just test